name: CI/CD

on:
  push:
    tags:
      - 'v*'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
    # Run npm install and build on our code
      - run: yarn install
      - run: yarn build --if-present

      - name: Deploy to netlify
        uses: actions/upload-artifact@v3
        
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

    # - name: Run the tests and generate coverage report
    #   run: yarn test -- --coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1

    # - name: Build
    #   run: yarn build

    # - name: Build & push Docker image
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     image: udokachi/live-project-front-end-image
    #     tags: latest
    #     registry: docker.io
    #     dockerfile: Dockerfile
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
